Traceback (most recent call last):
  File "spaceinvaders.py", line 22, in <module>
    for name in IMG_NAMES}
  File "spaceinvaders.py", line 22, in <dictcomp>
    for name in IMG_NAMES}
pygame.error: Couldn't open images/ship.png
Traceback (most recent call last):
  File "spaceinvaders.py", line 22, in <module>
    for name in IMG_NAMES}
  File "spaceinvaders.py", line 22, in <dictcomp>
    for name in IMG_NAMES}
pygame.error: Couldn't open images/ship.png
